name: Benchmark Webflux with Apache Benchmark

on:
  workflow_dispatch:

jobs:
  ab:
    runs-on: ubuntu-22.04
    env:
      GH: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto

      - name: Run Benchmarks
        run: |
          chmod +x ./bench-webflux.sh ../../code/gradlew ./run-ab.sh
          ./bench-webflux.sh
        working-directory:
            $GITHUB_WORKSPACE/benches/ab

      - name: List Github workspace contents
        run: ls -lR $GITHUB_WORKSPACE

      - name: Upload result artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results-ab-${{runner.os}}
          path: ${{ github.workspace }}/benches/ab/webflux-results.log
